export default {
    works: [{ id: 0,
            date: '',
            projName: '',
            workType: '',
            time: ''}],
    projTime: [{ id: 0,
               projN:'',
               projT:'' }],
    projNames: [],
    pr: [],
    tdate: '',
    tprojName: '',
    tworkType: '',
    ttime: '',
    startDate: '',
    endDate: '',
    period: 'Choose period',
    butType: 0,
    curNum: 0,
    worksChange: 0,
}
