export default {
  works: [{ id: 0,
            date: '',
            projName: '',
            workType: '',
            time: ''}],
  tdate: '',
  tprojName: '',
  tworkType: '',
  ttime: '',
  startDate: '',
  endDate: '',
  butType: 0,
  curNum: 0,
  worksChange: 0,
}
